version: '3.3'
services:
  web:
    container_name: savanamed_web
    build: .
    ports:
      - "${SAVANAMED_HTTP_PORT:-5000}:5000"
    volumes:
      - .:/flask-api
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${SAVANAMED_HTTP_PORT:-5000/status}/ || exit 1"]
    restart: on-failure
    environment:
      - FLASK_APP=savanamed/__init__.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://db:27017/
      - MONGO_DATABASE=savanamed_development
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=dsvv
    depends_on:
      - db
  db:
    container_name: savanamed_db
    image: mongo:4.4-bionic
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dsvv
    restart: always
    ports:
      - 27017:27017
volumes:
  mongo_data: